import {
  PrismaClient,
  VehicleType,
  DriveType,
  Prisma,
} from './generated/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});

const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('Очищаем старые данные...');

  await prisma.country.deleteMany();
  await prisma.vehicle.deleteMany();

  console.log('Заполняем таблицу Country...');

  const countriesData: Prisma.CountryCreateManyInput[] = [
    { Code: 'AF', Name: 'Афганистан' },
    { Code: 'AL', Name: 'Албания' },
    { Code: 'DZ', Name: 'Алжир' },
    { Code: 'AS', Name: 'Американское Самоа' },
    { Code: 'AD', Name: 'Андорра' },
    { Code: 'AO', Name: 'Ангола' },
    { Code: 'AI', Name: 'Ангилья' },
    { Code: 'AQ', Name: 'Антарктида' },
    { Code: 'AG', Name: 'Антигуа и Барбуда' },
    { Code: 'AR', Name: 'Аргентина' },
    { Code: 'AM', Name: 'Армения' },
    { Code: 'AW', Name: 'Аруба' },
    { Code: 'AU', Name: 'Австралия' },
    { Code: 'AT', Name: 'Австрия' },
    { Code: 'AZ', Name: 'Азербайджан' },
    { Code: 'BS', Name: 'Багамы' },
    { Code: 'BH', Name: 'Бахрейн' },
    { Code: 'BD', Name: 'Бангладеш' },
    { Code: 'BB', Name: 'Барбадос' },
    { Code: 'BY', Name: 'Беларусь' },
    { Code: 'BE', Name: 'Бельгия' },
    { Code: 'BZ', Name: 'Белиз' },
    { Code: 'BJ', Name: 'Бенин' },
    { Code: 'BM', Name: 'Бермуды' },
    { Code: 'BT', Name: 'Бутан' },
    { Code: 'BO', Name: 'Боливия' },
    { Code: 'BQ', Name: 'Бонайре, Синт-Эстатиус и Саба' },
    { Code: 'BA', Name: 'Босния и Герцеговина' },
    { Code: 'BW', Name: 'Ботсвана' },
    { Code: 'BV', Name: 'Остров Буве' },
    { Code: 'BR', Name: 'Бразилия' },
    { Code: 'IO', Name: 'Британская территория в Индийском океане' },
    { Code: 'BN', Name: 'Бруней-Даруссалам' },
    { Code: 'BG', Name: 'Болгария' },
    { Code: 'BF', Name: 'Буркина-Фасо' },
    { Code: 'BI', Name: 'Бурунди' },
    { Code: 'CV', Name: 'Кабо-Верде' },
    { Code: 'KH', Name: 'Камбоджа' },
    { Code: 'CM', Name: 'Камерун' },
    { Code: 'CA', Name: 'Канада' },
    { Code: 'KY', Name: 'Каймановы острова' },
    { Code: 'CF', Name: 'Центральноафриканская Республика' },
    { Code: 'TD', Name: 'Чад' },
    { Code: 'CL', Name: 'Чили' },
    { Code: 'CN', Name: 'Китай' },
    { Code: 'CX', Name: 'Остров Рождества' },
    { Code: 'CC', Name: 'Кокосовые (Килинг) острова' },
    { Code: 'CO', Name: 'Колумбия' },
    { Code: 'KM', Name: 'Коморы' },
    { Code: 'CD', Name: 'Конго, Демократическая Республика' },
    { Code: 'CG', Name: 'Конго' },
    { Code: 'CK', Name: 'Острова Кука' },
    { Code: 'CR', Name: 'Коста-Рика' },
    { Code: 'CI', Name: "Кот-д'Ивуар" },
    { Code: 'HR', Name: 'Хорватия' },
    { Code: 'CU', Name: 'Куба' },
    { Code: 'CW', Name: 'Кюрасао' },
    { Code: 'CY', Name: 'Кипр' },
    { Code: 'CZ', Name: 'Чехия' },
    { Code: 'DK', Name: 'Дания' },
    { Code: 'DJ', Name: 'Джибути' },
    { Code: 'DM', Name: 'Доминика' },
    { Code: 'DO', Name: 'Доминиканская Республика' },
    { Code: 'EC', Name: 'Эквадор' },
    { Code: 'EG', Name: 'Египет' },
    { Code: 'SV', Name: 'Сальвадор' },
    { Code: 'GQ', Name: 'Экваториальная Гвинея' },
    { Code: 'ER', Name: 'Эритрея' },
    { Code: 'EE', Name: 'Эстония' },
    { Code: 'SZ', Name: 'Эсватини' },
    { Code: 'ET', Name: 'Эфиопия' },
    { Code: 'FK', Name: 'Фолклендские острова (Мальвинские)' },
    { Code: 'FO', Name: 'Фарерские острова' },
    { Code: 'FJ', Name: 'Фиджи' },
    { Code: 'FI', Name: 'Финляндия' },
    { Code: 'FR', Name: 'Франция' },
    { Code: 'GF', Name: 'Французская Гвиана' },
    { Code: 'PF', Name: 'Французская Полинезия' },
    { Code: 'TF', Name: 'Французские Южные территории' },
    { Code: 'GA', Name: 'Габон' },
    { Code: 'GM', Name: 'Гамбия' },
    { Code: 'GE', Name: 'Грузия' },
    { Code: 'DE', Name: 'Германия' },
    { Code: 'GH', Name: 'Гана' },
    { Code: 'GI', Name: 'Гибралтар' },
    { Code: 'GR', Name: 'Греция' },
    { Code: 'GL', Name: 'Гренландия' },
    { Code: 'GD', Name: 'Гренада' },
    { Code: 'GP', Name: 'Гваделупа' },
    { Code: 'GU', Name: 'Гуам' },
    { Code: 'GT', Name: 'Гватемала' },
    { Code: 'GG', Name: 'Гернси' },
    { Code: 'GN', Name: 'Гвинея' },
    { Code: 'GW', Name: 'Гвинея-Бисау' },
    { Code: 'GY', Name: 'Гайана' },
    { Code: 'HT', Name: 'Гаити' },
    { Code: 'HM', Name: 'Херд и Макдональд, острова' },
    { Code: 'VA', Name: 'Святой Престол (Ватикан)' },
    { Code: 'HN', Name: 'Гондурас' },
    { Code: 'HK', Name: 'Гонконг' },
    { Code: 'HU', Name: 'Венгрия' },
    { Code: 'IS', Name: 'Исландия' },
    { Code: 'IN', Name: 'Индия' },
    { Code: 'ID', Name: 'Индонезия' },
    { Code: 'IR', Name: 'Иран, Исламская Республика' },
    { Code: 'IQ', Name: 'Ирак' },
    { Code: 'IE', Name: 'Ирландия' },
    { Code: 'IM', Name: 'Остров Мэн' },
    { Code: 'IL', Name: 'Израиль' },
    { Code: 'IT', Name: 'Италия' },
    { Code: 'JM', Name: 'Ямайка' },
    { Code: 'JP', Name: 'Япония' },
    { Code: 'JE', Name: 'Джерси' },
    { Code: 'JO', Name: 'Иордания' },
    { Code: 'KZ', Name: 'Казахстан' },
    { Code: 'KE', Name: 'Кения' },
    { Code: 'KI', Name: 'Кирибати' },
    { Code: 'KP', Name: 'Корейская Народно-Демократическая Республика (КНДР)' },
    { Code: 'KR', Name: 'Республика Корея (Южная Корея)' },
    { Code: 'KW', Name: 'Кувейт' },
    { Code: 'KG', Name: 'Киргизия' },
    { Code: 'LA', Name: 'Лаосская Народно-Демократическая Республика' },
    { Code: 'LV', Name: 'Латвия' },
    { Code: 'LB', Name: 'Ливан' },
    { Code: 'LS', Name: 'Лесото' },
    { Code: 'LR', Name: 'Либерия' },
    { Code: 'LY', Name: 'Ливия' },
    { Code: 'LI', Name: 'Лихтенштейн' },
    { Code: 'LT', Name: 'Литва' },
    { Code: 'LU', Name: 'Люксембург' },
    { Code: 'MO', Name: 'Макао' },
    { Code: 'MG', Name: 'Мадагаскар' },
    { Code: 'MW', Name: 'Малави' },
    { Code: 'MY', Name: 'Малайзия' },
    { Code: 'MV', Name: 'Мальдивы' },
    { Code: 'ML', Name: 'Мали' },
    { Code: 'MT', Name: 'Мальта' },
    { Code: 'MH', Name: 'Маршалловы острова' },
    { Code: 'MQ', Name: 'Мартиника' },
    { Code: 'MR', Name: 'Мавритания' },
    { Code: 'MU', Name: 'Маврикий' },
    { Code: 'YT', Name: 'Майотта' },
    { Code: 'MX', Name: 'Мексика' },
    { Code: 'FM', Name: 'Микронезия, Федеративные Штаты' },
    { Code: 'MD', Name: 'Молдова, Республика' },
    { Code: 'MC', Name: 'Монако' },
    { Code: 'MN', Name: 'Монголия' },
    { Code: 'ME', Name: 'Черногория' },
    { Code: 'MS', Name: 'Монтсеррат' },
    { Code: 'MA', Name: 'Марокко' },
    { Code: 'MZ', Name: 'Мозамбик' },
    { Code: 'MM', Name: 'Мьянма' },
    { Code: 'NA', Name: 'Намибия' },
    { Code: 'NR', Name: 'Науру' },
    { Code: 'NP', Name: 'Непал' },
    { Code: 'NL', Name: 'Нидерланды' },
    { Code: 'NC', Name: 'Новая Каледония' },
    { Code: 'NZ', Name: 'Новая Зеландия' },
    { Code: 'NI', Name: 'Никарагуа' },
    { Code: 'NE', Name: 'Нигер' },
    { Code: 'NG', Name: 'Нигерия' },
    { Code: 'NU', Name: 'Ниуэ' },
    { Code: 'NF', Name: 'Остров Норфолк' },
    { Code: 'MK', Name: 'Северная Македония' },
    { Code: 'MP', Name: 'Северные Марианские острова' },
    { Code: 'NO', Name: 'Норвегия' },
    { Code: 'OM', Name: 'Оман' },
    { Code: 'PK', Name: 'Пакистан' },
    { Code: 'PW', Name: 'Палау' },
    { Code: 'PS', Name: 'Палестина, Государство' },
    { Code: 'PA', Name: 'Панама' },
    { Code: 'PG', Name: 'Папуа - Новая Гвинея' },
    { Code: 'PY', Name: 'Парагвай' },
    { Code: 'PE', Name: 'Перу' },
    { Code: 'PH', Name: 'Филиппины' },
    { Code: 'PN', Name: 'Питкэрн' },
    { Code: 'PL', Name: 'Польша' },
    { Code: 'PT', Name: 'Португалия' },
    { Code: 'PR', Name: 'Пуэрто-Рико' },
    { Code: 'QA', Name: 'Катар' },
    { Code: 'RE', Name: 'Реюньон' },
    { Code: 'RO', Name: 'Румыния' },
    { Code: 'RU', Name: 'Россия' },
    { Code: 'RW', Name: 'Руанда' },
    { Code: 'BL', Name: 'Сен-Бартельми' },
    { Code: 'SH', Name: 'Острова Святой Елены, Вознесения и Тристан-да-Кунья' },
    { Code: 'KN', Name: 'Сент-Китс и Невис' },
    { Code: 'LC', Name: 'Сент-Люсия' },
    { Code: 'MF', Name: 'Сен-Мартен (французская часть)' },
    { Code: 'PM', Name: 'Сен-Пьер и Микелон' },
    { Code: 'VC', Name: 'Сент-Винсент и Гренадины' },
    { Code: 'WS', Name: 'Самоа' },
    { Code: 'SM', Name: 'Сан-Марино' },
    { Code: 'ST', Name: 'Сан-Томе и Принсипи' },
    { Code: 'SA', Name: 'Саудовская Аравия' },
    { Code: 'SN', Name: 'Сенегал' },
    { Code: 'RS', Name: 'Сербия' },
    { Code: 'SC', Name: 'Сейшельские острова' },
    { Code: 'SL', Name: 'Сьерра-Леоне' },
    { Code: 'SG', Name: 'Сингапур' },
    { Code: 'SX', Name: 'Синт-Мартен (нидерландская часть)' },
    { Code: 'SK', Name: 'Словакия' },
    { Code: 'SI', Name: 'Словения' },
    { Code: 'SB', Name: 'Соломоновы острова' },
    { Code: 'SO', Name: 'Сомали' },
    { Code: 'ZA', Name: 'Южная Африка' },
    { Code: 'GS', Name: 'Южная Георгия и Южные Сандвичевы острова' },
    { Code: 'SS', Name: 'Южный Судан' },
    { Code: 'ES', Name: 'Испания' },
    { Code: 'LK', Name: 'Шри-Ланка' },
    { Code: 'SD', Name: 'Судан' },
    { Code: 'SR', Name: 'Суринам' },
    { Code: 'SJ', Name: 'Шпицберген и Ян-Майен' },
    { Code: 'SE', Name: 'Швеция' },
    { Code: 'CH', Name: 'Швейцария' },
    { Code: 'SY', Name: 'Сирийская Арабская Республика' },
    { Code: 'TW', Name: 'Тайвань (Китай)' },
    { Code: 'TJ', Name: 'Таджикистан' },
    { Code: 'TZ', Name: 'Танзания, Объединенная Республика' },
    { Code: 'TH', Name: 'Таиланд' },
    { Code: 'TL', Name: 'Тимор-Лешти' },
    { Code: 'TG', Name: 'Того' },
    { Code: 'TK', Name: 'Токелау' },
    { Code: 'TO', Name: 'Тонга' },
    { Code: 'TT', Name: 'Тринидад и Тобаго' },
    { Code: 'TN', Name: 'Тунис' },
    { Code: 'TR', Name: 'Турция' },
    { Code: 'TM', Name: 'Туркменистан' },
    { Code: 'TC', Name: 'Теркс и Кайкос, острова' },
    { Code: 'TV', Name: 'Тувалу' },
    { Code: 'UG', Name: 'Уганда' },
    { Code: 'UA', Name: 'Украина' },
    { Code: 'AE', Name: 'Объединенные Арабские Эмираты' },
    { Code: 'GB', Name: 'Великобритания' },
    { Code: 'US', Name: 'США' },
    { Code: 'UM', Name: 'Малые Тихоокеанские отдаленные острова США' },
    { Code: 'UY', Name: 'Уругвай' },
    { Code: 'UZ', Name: 'Узбекистан' },
    { Code: 'VU', Name: 'Вануату' },
    { Code: 'VE', Name: 'Венесуэла (Боливарианская Республика)' },
    { Code: 'VN', Name: 'Вьетнам' },
    { Code: 'VG', Name: 'Виргинские острова, Британские' },
    { Code: 'VI', Name: 'Виргинские острова, США' },
    { Code: 'WF', Name: 'Уоллис и Футуна' },
    { Code: 'EH', Name: 'Западная Сахара' },
    { Code: 'YE', Name: 'Йемен' },
    { Code: 'ZM', Name: 'Замбия' },
    { Code: 'ZW', Name: 'Зимбабве' },
  ];

  await prisma.country.createMany({
    data: countriesData,
  });

  console.log('Таблица Country заполнена.');

  console.log('Заполняем таблицу Vehicle...');

  // Получаем ID стран для связи
  const russia = await prisma.country.findFirstOrThrow({
    where: { Code: 'RU' },
  });
  const us = await prisma.country.findFirstOrThrow({ where: { Code: 'US' } });
  const germany = await prisma.country.findFirstOrThrow({
    where: { Code: 'DE' },
  });
  const japan = await prisma.country.findFirstOrThrow({
    where: { Code: 'JP' },
  });
  const france = await prisma.country.findFirstOrThrow({
    where: { Code: 'FR' },
  });
  const italy = await prisma.country.findFirstOrThrow({
    where: { Code: 'IT' },
  });
  const korea = await prisma.country.findFirstOrThrow({
    where: { Code: 'KR' },
  });
  const gb = await prisma.country.findFirstOrThrow({
    where: { Code: 'GB' },
  });
  const cz = await prisma.country.findFirstOrThrow({
    where: { Code: 'CZ' },
  });

  const vehiclesData: Prisma.VehicleCreateManyInput[] = [
    {
      name: 'Toyota Camry',
      weight: 1500,
      height: 1450,
      width: 1840,
      length: 4885,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Надежный седан для повседневной эксплуатации.',
      engineCapacity: 2500,
      isElectro: false,
      driveType: DriveType.FWD,
      countryId: japan.id,
    },
    {
      name: 'BMW X5',
      weight: 2100,
      height: 1772,
      width: 2000,
      length: 4930,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Полноразмерный премиальный кроссовер.',
      engineCapacity: 3000,
      isElectro: false,
      driveType: DriveType.AWD,
      countryId: germany.id,
    },
    {
      name: 'Tesla Model S',
      weight: 2250,
      height: 1440,
      width: 1964,
      length: 4970,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Электрический седан с высокой производительностью.',
      engineCapacity: 0, // Electric
      isElectro: true,
      driveType: DriveType.AWD,
      countryId: us.id,
    },
    {
      name: 'Lada Vesta',
      weight: 1200,
      height: 1500,
      width: 1700,
      length: 4400,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Надежный российский седан.',
      engineCapacity: 1800,
      isElectro: false,
      driveType: DriveType.FWD,
      countryId: russia.id,
    },
    {
      name: 'Ford Mustang',
      weight: 1750,
      height: 1390,
      width: 1916,
      length: 4790,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Классический американский мускульный автомобиль.',
      engineCapacity: 5000,
      isElectro: false,
      driveType: DriveType.RWD,
      countryId: us.id,
    },
    {
      name: 'Honda Civic',
      weight: 1300,
      height: 1420,
      width: 1770,
      length: 4650,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Экономичный и надежный хэтчбек.',
      engineCapacity: 1600,
      isElectro: false,
      driveType: DriveType.FWD,
      countryId: japan.id,
    },
    {
      name: 'Audi A4',
      weight: 1550,
      height: 1430,
      width: 1850,
      length: 4720,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Премиальный седан с отличной управляемостью.',
      engineCapacity: 2000,
      isElectro: false,
      driveType: DriveType.AWD,
      countryId: germany.id,
    },
    {
      name: 'Nissan Qashqai',
      weight: 1450,
      height: 1620,
      width: 1820,
      length: 4394,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Популярный кроссовер для города и за его пределами.',
      engineCapacity: 1600,
      isElectro: false,
      driveType: DriveType.FWD,
      countryId: japan.id,
    },
    {
      name: 'Mercedes-Benz C-Class',
      weight: 1600,
      height: 1440,
      width: 1810,
      length: 4686,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Комфортный и технологичный бизнес-седан.',
      engineCapacity: 2000,
      isElectro: false,
      driveType: DriveType.RWD,
      countryId: germany.id,
    },
    {
      name: 'Volkswagen Golf',
      weight: 1350,
      height: 1450,
      width: 1799,
      length: 4255,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Классический европейский хэтчбек.',
      engineCapacity: 1400,
      isElectro: false,
      driveType: DriveType.FWD,
      countryId: germany.id,
    },
    {
      name: 'Hyundai Tucson',
      weight: 1550,
      height: 1650,
      width: 1850,
      length: 4480,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Современный и комфортабельный кроссовер.',
      engineCapacity: 2000,
      isElectro: false,
      driveType: DriveType.AWD,
      countryId: korea.id,
    },
    {
      name: 'KIA Rio',
      weight: 1250,
      height: 1475,
      width: 1725,
      length: 4340,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Надежный и экономичный седан от корейского производителя.',
      engineCapacity: 1600,
      isElectro: false,
      driveType: DriveType.FWD,
      countryId: korea.id,
    },
    {
      name: 'Peugeot 308',
      weight: 1300,
      height: 1460,
      width: 1820,
      length: 4550,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Стильный французский хэтчбек.',
      engineCapacity: 1200,
      isElectro: false,
      driveType: DriveType.FWD,
      countryId: france.id,
    },
    {
      name: 'Fiat 500',
      weight: 1100,
      height: 1500,
      width: 1630,
      length: 3550,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Компактный и маневренный городской автомобиль.',
      engineCapacity: 1000,
      isElectro: false,
      driveType: DriveType.FWD,
      countryId: italy.id,
    },
    {
      name: 'Land Rover Defender',
      weight: 2500,
      height: 1930,
      width: 2110,
      length: 5018,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Легендарный внедорожник с высокой проходимостью.',
      engineCapacity: 3000,
      isElectro: false,
      driveType: DriveType.AWD,
      countryId: gb.id,
    },
    {
      name: 'Porsche 911',
      weight: 1450,
      height: 1300,
      width: 1852,
      length: 4519,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Спорткар с отличной динамикой и управляемостью.',
      engineCapacity: 3800,
      isElectro: false,
      driveType: DriveType.RWD,
      countryId: germany.id,
    },
    {
      name: 'Chevrolet Camaro',
      weight: 1700,
      height: 1390,
      width: 1900,
      length: 4786,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Американский мускульный автомобиль, конкурент Mustang.',
      engineCapacity: 6200,
      isElectro: false,
      driveType: DriveType.RWD,
      countryId: us.id,
    },
    {
      name: 'Mazda CX-5',
      weight: 1520,
      height: 1680,
      width: 1840,
      length: 4550,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Комфортабельный и динамичный кроссовер японского производства.',
      engineCapacity: 2500,
      isElectro: false,
      driveType: DriveType.AWD,
      countryId: japan.id,
    },
    {
      name: 'Renault Duster',
      weight: 1400,
      height: 1650,
      width: 1822,
      length: 4341,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Надежный и доступный кроссовер с высокой проходимостью.',
      engineCapacity: 1600,
      isElectro: false,
      driveType: DriveType.AWD,
      countryId: france.id,
    },
    {
      name: 'Skoda Octavia',
      weight: 1350,
      height: 1470,
      width: 1814,
      length: 4689,
      vehicleType: VehicleType.AutoVehicle,
      desc: 'Просторный и практичный хэтчбек чешского производства.',
      engineCapacity: 1400,
      isElectro: false,
      driveType: DriveType.FWD,
      countryId: cz.id,
    },
  ];

  await prisma.vehicle.createMany({
    data: vehiclesData,
  });

  console.log('Таблица Vehicle заполнена.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma?.$disconnect();
  });
